server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
              - Path=/api/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
              - Path=/api/hotels/**

        - id: QUALIFICATION-SERVICE
          uri: lb://QUALIFICATION-SERVICE
          predicates:
            - Path=/api/qualifications/**

